# Form implementation generated from reading ui file 'd:\深度学习实践\main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
### 通过 qtdesigner 打造的页面设计
from PyQt6 import QtCore, QtGui, QtWidgets
    

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # 创建三个小窗口
        self.window1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.window1.setGeometry(QtCore.QRect(100, 100, 200, 200))
        self.window1.setText("Window 1")
        self.window1.hide()

        self.window2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.window2.setGeometry(QtCore.QRect(350, 100, 200, 200))
        self.window2.setText("Window 2")
        self.window2.hide()

        self.window3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.window3.setGeometry(QtCore.QRect(600, 100, 200, 200))
        self.window3.setText("Window 3")
        self.window3.hide()

        # 创建切换按钮
        self.button1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button1.setGeometry(QtCore.QRect(50, 400, 75, 24))
        self.button1.setObjectName("button1")
        self.button1.clicked.connect(self.showWindow1)

        self.button2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button2.setGeometry(QtCore.QRect(300, 400, 75, 24))
        self.button2.setObjectName("button2")
        self.button2.clicked.connect(self.showWindow2)

        self.button3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button3.setGeometry(QtCore.QRect(550, 400, 75, 24))
        self.button3.setObjectName("button3")
        self.button3.clicked.connect(self.showWindow3)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button1.setText(_translate("MainWindow", "Window 1"))
        self.button2.setText(_translate("MainWindow", "Window 2"))
        self.button3.setText(_translate("MainWindow", "Window 3"))

    def showWindow1(self):
        self.window1.show()
        self.window2.hide()
        self.window3.hide()

    def showWindow2(self):
        self.window1.hide()
        self.window2.show()
        self.window3.hide()

    def showWindow3(self):
        self.window1.hide()
        self.window2.hide()
        self.window3.show()
if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()

    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)

    MainWindow.show()
    sys.exit(app.exec()
